Tomandersen/run update proto script
googleapis/nodejs-firestore pull request #1767
Opened 2022-09-07 20:08 UTC by tom-andersen

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-firestore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2022-09-07 20:42 UTC, dconeybe approved these changes

2022-09-08 17:22 UTC, dconeybe requested changes
I'm withdrawing my approval because we don't want stuff from the googleapis preview branch going into the main branch of this repo.

2022-09-14 22:34 UTC, alexander-fenster commented
To give you some context, the initial idea of `update.sh` was to split protos into smaller files, and load them separately as needed, which should improve cold start time. This is a unique thing, no other client libraries do this. I haven't looked at why the preview features get included though, the script might need some fixing. Feel free to ping me if you want extra 👀 to look at it.

2022-09-16 07:54 UTC, alexander-fenster commented on dev/protos/update.sh
> +git clone -b preview --depth 1 https://github.com/googleapis/googleapis.git
Why `-b preview`?

2022-09-16 07:55 UTC, alexander-fenster commented
In #1765 I updated protos with the latest updates from googleapis. I'm assuming this PR could be closed now.

2022-09-16 14:07 UTC, closed without merging