Markduckworth/findnearest
googleapis/nodejs-firestore pull request #2006
Opened 2024-03-04 17:52 UTC by MarkDuckworth

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-firestore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-03-11 14:14 UTC, wu-hui approved these changes

2024-03-25 15:03 UTC, wu-hui approved these changes
I reviewed by commits, maybe my comments no longer apply if you already fixed them in a different commits. 

The comments are minor anyways, so LGTM!

2024-03-27 21:56 UTC, sofisl requested changes
Please remove the breaking changes:

```query._stream --> query._queryUtil._stream
query.toProto() --> query._toProto()```

for this release

2024-03-28 01:17 UTC, sofisl commented on dev/src/reference.ts
> - * A Query refers to a query which you can read or stream from. You can also
Isn't removing the Query class and changing it for QueryUtil a breaking change as well?

2024-03-28 01:22 UTC, sofisl approved these changes

2024-04-02 17:34 UTC, merged