Fix: sort document reference by long type id
googleapis/nodejs-firestore pull request #2257
Opened 2024-12-06 21:41 UTC by milaGGL

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-firestore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-12-06 22:27 UTC, milaGGL commented on dev/system-test/firestore.ts
> +    it('snapshot listener sorts query by DocumentId same way as server', async () => {
add negative number id

2024-12-11 21:30 UTC, ehsannas requested changes

2024-12-12 18:54 UTC, milaGGL commented on dev/src/path.ts
> +      return Math.sign(this.extractNumericId(lhs) - this.extractNumericId(rhs));
good point.

2024-12-12 21:31 UTC, ehsannas approved these changes

2024-12-12 21:50 UTC, ehsannas approved these changes

2024-12-12 21:50 UTC, ehsannas commented on dev/src/path.ts
> +    );
ultra-nit [feel free to ignore]: segment lengths are usually very small positive numbers.
Doing `return Math.sign(this.segments.length - other.segments.length);` is slightly better than converting to BigInt and then comparing.

2024-12-17 16:11 UTC, merged